version: '2'

services:
    ns:
        build:
            context: yadfs
            dockerfile: ns/Dockerfile
        image: yadfs:ns
        tty: true
        stdin_open: true
    cs:
        build:
            context: yadfs
            dockerfile: cs/Dockerfile
        image: yadfs:cs
        tty: true
        stdin_open: true
        environment:
            YAD_NS: http://ns:8888
        depends_on:
            - ns
        links:
            - ns
    jt:
        build:
            context: .
            dockerfile: Dockerfile.jt
        image: yamr:jt
        tty: true
        stdin_open: true
        environment:
            YAD_NS: http://ns:8888
        depends_on:
            - ns
            - cs
        links:
            - ns
            - cs
    worker:
        build:
            context: .
            dockerfile: Dockerfile.worker
        image: yamr:worker
        tty: true
        stdin_open: true
        environment:
            YAD_NS: http://ns:8888
        depends_on:
            - jt
            - ns
            - cs
        links:
            - jt
            - ns
            - cs
    mr_client:
        build:
            context: .
            dockerfile: Dockerfile.client
        image: yamr:client
        tty: true
        stdin_open: true
        environment:
            YAD_NS: http://ns:8888
            YAMR_JT: http://jt:11111
        depends_on:
            - jt
            - ns
            - cs
            - worker
        links:
            - jt
            - ns
            - cs
            - worker